### ISSUE TITLE
Build Failure on toolchain v15.0

### ISSUE THREAD

**Issue by ezntek** [KhiCAS/ti-ce#12]
When running `./mkappen` on Gentoo Linux x86_64, the build fails on CEdev toolchain v14.2 this way:

```
[compiling] src/main.cc
/opt/CEdev/bin/ez80-clang: /usr/lib64/libtinfo.so.6: no version information available (required by /opt/CEdev/bin/ez80-clang)
[compiling] src/menufr.cc
/opt/CEdev/bin/ez80-clang: /usr/lib64/libtinfo.so.6: no version information available (required by /opt/CEdev/bin/ez80-clang)
src/menufr.cc:2:10: fatal error: 'giac/giacPCH.h' file not found
#include <giac/giacPCH.h>
         ^~~~~~~~~~~~~~~~
src/main.cc:7:10: fatal error: 'giac/giacPCH.h' file not found
#include <giac/giacPCH.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make: *** [/opt/CEdev/meta/makefile.mk:352: obj/src/menufr.cc.bc] Error 1
make: *** Waiting for unfinished jobs....
1 error generated.
make: *** [/opt/CEdev/meta/makefile.mk:352: obj/src/main.cc.bc] Error 1
```

And on version 15:

```
make: *** No rule to make target 'bin/', needed by 'bin/DEMO.8ek'.  Stop.
```

This is jsut a standard Gentoo installation, with no weird libraries and such.

**Comment by ezntek** [comment]
Update: I ran `git submodule update --init --recursive`, which pulled in giac. The build seems to just fine on v14.2.

**Comment by adriweb** [comment]
Yes this is likely not ever going to be compatible with v15 which changed underlying things in ways that would take a long time for this project to adapt to. For now it's simple enough to build with v14.2 that's ok.

But indeed you need to clone recursively (or fetch the submodules after cloning)!
